# Generated by Django 5.1.3 on 2024-11-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prescription_required",
            field=models.BooleanField(default=True),
        ),
    ]
